version: '3.8'

services:
  # Serviço do Backend
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app                # Código do backend
      - shared_graphs:/shared_graphs  # Volume compartilhado para gráficos
    env_file:
      - ./backend/.env
    depends_on:
      - cache

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
      - shared_graphs:/shared_graphs  # Mesmo volume do backend
    depends_on:
      - backend

  # Serviço de Cache (Redis)
  cache:
    image: "redis:alpine"
    ports:
      - "6379:6379"

# Volumes compartilhados
volumes:
  shared_graphs:
